GET http://localhost:5281/getDatabases HTTP/1.1
Authorization: Bearer CfDJ8KkI2x9pSWNDpSOUrcmK-fZGsZaRzA0Yr10ifkk-DrQdlFWor5libYiU34mMm3hywhWVI8asn36qQVVr8lDU9krppUQWxIT5w4AVxlJ_J_HWWZvgGMAi5QkRyM3L-Y2O3rWQXhrYB6MbwH4TsFZT6fTlzs0yhJ-spkbTkADugvatOXRNzri2QTF_Txy-cn1AY1BPy8Z0ZD_u5hvJRldV2JwOqaWH3tcShJGI3cD2gplApS_Icyg4FCEtW-t7xGxoZAyskt3QUSLnThwlFQw-Jcw
Content-Type: application/json