POST http://localhost:5281/createUser HTTP/1.1
Content-Type: application/json
Authorization: Bearer CfDJ8KkI2x9pSWNDpSOUrcmK-fZcQizk4WXXhHScuUF82etnTPhSxqwf0f_ic6bbXftdFwAH1jzxOK41smyOrAltZv7Idxaj4JyPp_2Q2GEmfPUbenBPxTm5fFKHfF_-GgXXQP6n0QOUowu4D3IGsI7_c_BYPozFOYPf1_gTEngJ5p1cqawAmek3EdYdKhNSzJKw0W6HYxwIVzvROv_PvT4mNfVS-4ygFb0KtPDHGexpDUeU7OW-T8XhpFz8cj8A0ABVW20qZWtzOo3xgKCHr38Qzc0

{
    "Username": "christoph",
    "Password": "123456"
}
