POST http://localhost:5281/customQuery HTTP/1.1
Authorization: Bearer CfDJ8KkI2x9pSWNDpSOUrcmK-fao5_BWeX7v9LBxzRQWseTV7eSGPqL7rMPx-toJ22JN-IgsXZdJqxmB1hzgADtdKM9u66iBFCYezNdY7mJu8p8NZmfeDw6UwwR8M6tH809-w6eW7LFYEufrpgJpzD4MTNxkS9AeKJzX2AU038xZkuNONY5qyAIMEJqwcfL9B4NT_AFA2cUh9WOHImf2hERqI_k9hSrJ7M1NUgUvPALDsY9sw796aAvSDAPuPgZZHx1-ZKI38EvdIwKFxWe0dR6ty6I
Content-Type: application/json

//"SELECT Name, Vorname, toString(Geburtsdatum) FROM Patienten WHERE Name = 'Mueller'"
"U0VMRUNUIE5hbWUsIFZvcm5hbWUsIHRvU3RyaW5nKEdlYnVydHNkYXR1bSkgRlJPTSBQYXRpZW50ZW4gV0hFUkUgTmFtZSA9ICdNdWVsbGVyJw=="

